name: 'AKS Deployment'

on:
  push:
    branches:
      - master  # Adjust this to match the branch where you want to trigger the workflow

permissions:
  contents: read


jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: self-hosted
    environment: development

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: aks-terraform

      - name: Terraform Format
        run: terraform fmt
        working-directory: aks-terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: aks-terraform

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
