name: 'AKS Deployment'

on:
  push:
    branches:
      - main  # Adjust this to match the branch where you want to trigger the workflow

permissions:
  contents: read

runs-on: self-hosted

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: aks-terraform
        run: terraform init

      - name: Terraform Format
        working-directory: aks-terraform
        run: terraform fmt

      - name: Terraform Plan
        working-directory: aks-terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: aks-terraform
        run: terraform apply -auto-approve
